### PR TITLE
Add CAVE/USDC

### PR DESCRIPTION
**Pull request by israelidanny**
## I agree to not ping _anybody_ on Discord/Twitter/Email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and can take up to **two weeks** to be merged.

**Please provide the following information for your serum market.**

Please include change to the `src/markets.json` file in the PR.
DON'T modify any other token on the list or your PR will be rejected.

Please fill in the information below along with the PR:

- Market Address: KrGK6ZHyE7Nt35D7GqAKJYAYUPUysGtVBgTXsJuAxMT
- Token Symbol: CAVE
- Link to the official homepage of token: https://cryptocavemen.io

### CODE REVIEW

**Comment by ebramanti** [comment]
Thanks for the contribution @israelidanny, can you please rebase? Happy to merge this.

**Comment by israelidanny** [comment]
@ebramanti done :)

**Comment by israelidanny** [comment]
Anything else needed to merge this?

**Comment by ebramanti** [comment]
Sorry for the delay on this, getting it merged now. Thanks for your contribution!

**Pull request merged**
